// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchInbound(arg1, arg2) {
  return window['go']['desktop']['App']['BatchInbound'](arg1, arg2);
}

export function BatchOutbound(arg1, arg2) {
  return window['go']['desktop']['App']['BatchOutbound'](arg1, arg2);
}

export function CheckReplenishment(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['CheckReplenishment'](arg1, arg2, arg3);
}

export function CreateAccessory(arg1, arg2) {
  return window['go']['desktop']['App']['CreateAccessory'](arg1, arg2);
}

export function DeleteAccessory(arg1, arg2) {
  return window['go']['desktop']['App']['DeleteAccessory'](arg1, arg2);
}

export function GetAccessory(arg1, arg2) {
  return window['go']['desktop']['App']['GetAccessory'](arg1, arg2);
}

export function GetAccessoryBySKU(arg1, arg2) {
  return window['go']['desktop']['App']['GetAccessoryBySKU'](arg1, arg2);
}

export function GetFlow(arg1, arg2) {
  return window['go']['desktop']['App']['GetFlow'](arg1, arg2);
}

export function Inbound(arg1, arg2) {
  return window['go']['desktop']['App']['Inbound'](arg1, arg2);
}

export function IsServerRunning() {
  return window['go']['desktop']['App']['IsServerRunning']();
}

export function ListAccessories(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['ListAccessories'](arg1, arg2, arg3, arg4);
}

export function ListFlows(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['desktop']['App']['ListFlows'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListFlowsByAccessory(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['desktop']['App']['ListFlowsByAccessory'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Outbound(arg1, arg2) {
  return window['go']['desktop']['App']['Outbound'](arg1, arg2);
}

export function ScanShortage(arg1) {
  return window['go']['desktop']['App']['ScanShortage'](arg1);
}

export function ServerAddr() {
  return window['go']['desktop']['App']['ServerAddr']();
}

export function SetConfig(arg1) {
  return window['go']['desktop']['App']['SetConfig'](arg1);
}

export function SetContext(arg1) {
  return window['go']['desktop']['App']['SetContext'](arg1);
}

export function StartServer() {
  return window['go']['desktop']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['desktop']['App']['StopServer']();
}

export function UpdateAccessory(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['UpdateAccessory'](arg1, arg2, arg3);
}
