// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {service} from '../models';
import {domain} from '../models';
import {config} from '../models';

export function BatchInbound(arg1:context.Context,arg2:Array<service.InboundCmd>):Promise<service.BatchResult>;

export function BatchOutbound(arg1:context.Context,arg2:Array<service.OutboundCmd>):Promise<service.BatchResult>;

export function CheckReplenishment(arg1:context.Context,arg2:Array<string>,arg3:string):Promise<service.BatchCheckResult>;

export function CreateAccessory(arg1:context.Context,arg2:domain.Accessory):Promise<domain.Accessory>;

export function DeleteAccessory(arg1:context.Context,arg2:number):Promise<void>;

export function GetAccessory(arg1:context.Context,arg2:number):Promise<domain.Accessory>;

export function GetAccessoryByName(arg1:context.Context,arg2:string):Promise<domain.Accessory>;

export function GetFlow(arg1:context.Context,arg2:number):Promise<domain.InventoryFlow>;

export function Inbound(arg1:context.Context,arg2:service.InboundCmd):Promise<domain.InventoryFlow>;

export function IsServerRunning():Promise<boolean>;

export function ListAccessories(arg1:context.Context,arg2:string,arg3:number,arg4:number):Promise<Array<domain.Accessory>>;

export function ListFlows(arg1:context.Context,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Array<domain.InventoryFlow>>;

export function ListFlowsByAccessory(arg1:context.Context,arg2:number,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<Array<domain.InventoryFlow>>;

export function Outbound(arg1:context.Context,arg2:service.OutboundCmd):Promise<domain.InventoryFlow>;

export function ScanShortage(arg1:context.Context):Promise<Array<service.ReplenishmentItem>>;

export function ServerAddr():Promise<string>;

export function SetConfig(arg1:config.Config):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UpdateAccessory(arg1:context.Context,arg2:number,arg3:domain.AccessoryUpdate):Promise<domain.Accessory>;
